[api_keys]
tmdb = "32f9a754dffed593776c81092af74920"
openai = "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"
