[api_keys]
tmdb = "32f9a754dffed593776c81092af74920"
openai = "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"
